on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Scan container image with Tenable Cloud Security
      uses: ermetic/actions/container-image/scan@v1
      with:
        api-token: ${{ secrets.TENABLE_API_TOKEN }}
        api-url: https://us2.app.ermetic.com
        name: "<place your image name here>"
