on:
  schedule:
    # * is a special character in YAML so you have to quote this string  
    - cron:  '1 */6 * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest  # Specify the type of virtual host machine to run the job on
    steps:
      - uses: actions/checkout@v3
      - name: Scan IaC with Tenable Cloud Security
        uses: ermetic/actions/iac/scan@v1
        with:
          api-token: ${{ secrets.TENABLE_API_TOKEN }}
          api-url: https://us2.app.ermetic.com
