name: Terrascan Code Scan

on: [push]

permissions:
  contents: read
  security-events: write

jobs:
  terrascan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        iac_type: [terraform, cft]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List IaC files in ${{ matrix.iac_type }}
        run: |
          echo "Looking inside '${{ matrix.iac_type }}'"
          find ${{ matrix.iac_type }} -type f \( -name "*.tf" -o -name "*.yaml" -o -name "*.yml" -o -name "*.json" \)

      - name: Run Terrascan via Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/iac \
            -w /iac \
            accurics/terrascan \
            scan -i ${{ matrix.iac_type }} -d . -o sarif > terrascan-${{ matrix.iac_type }}.sarif

      - name: Debug SARIF output
        if: always()
        run: |
          echo "Checking SARIF output for ${{ matrix.iac_type }}"
          ls -l terrascan-${{ matrix.iac_type }}.sarif || echo "File not found"
          cat terrascan-${{ matrix.iac_type }}.sarif || echo "File is empty"

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: terrascan-${{ matrix.iac_type }}.sarif
          category: ${{ matrix.iac_type }}
