name: Terrascan Code Scan

on: [push]

permissions:
  contents: read
  security-events: write  # Required to upload SARIF files

jobs:
  terrascan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        iac_type: [terraform, cft]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Terrascan for ${{ matrix.iac_type }}
        id: terrascan
        uses: accurics/terrascan-action@main
        with:
          iac_type: ${{ matrix.iac_type }}
          iac_dir: ${{ matrix.iac_type }}
          only_warn: true
          sarif_upload: true
          output_file: terrascan-${{ matrix.iac_type }}.sarif
          
      - name: Rename SARIF output
        run: mv terrascan.sarif terrascan-${{ matrix.iac_type }}.sarif
        
      - name: Debug SARIF output
        if: always()
        run: |
          echo "Checking SARIF output for ${{ matrix.iac_type }}"
          ls -l terrascan-${{ matrix.iac_type }}.sarif || echo "File not found"
          cat terrascan-${{ matrix.iac_type }}.sarif || echo "File is empty"

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: terrascan-${{ matrix.iac_type }}.sarif
          category: ${{ matrix.iac_type }}
