name: Terrascan Code Scan

on: [push]

permissions:
  contents: read
  security-events: write

jobs:
  terrascan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        iac_type: [terraform, cft]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List IaC files in ${{ matrix.iac_type }}
        run: |
          echo "Scanning contents of ./${{ matrix.iac_type }}"
          find ${{ matrix.iac_type }} -type f \( -name "*.tf" -o -name "*.yaml" -o -name "*.yml" -o -name "*.json" \) || echo "No files found."

      - name: Run Terrascan
        id: terrascan
        uses: tenable/terrascan-action@main
        with:
          iac_type: ${{ matrix.iac_type }}
          iac_version: v14
          policy_type: aws
          only_warn: true
          sarif_upload: true
          iac_dir: ${{ matrix.iac_type }}

      - name: Check SARIF output
        run: |
          if [ ! -s terrascan.sarif ]; then
            echo "⚠️ terrascan.sarif not found or empty for ${{ matrix.iac_type }}. Skipping upload."
            exit 0
          fi
          echo "✅ terrascan.sarif exists and is non-empty."

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: terrascan.sarif
          category: ${{ matrix.iac_type }}
